### ISSUE TITLE
Store values from page content

### ISSUE THREAD

**Issue by sbathke** [automate-website/waml#10]
it could be helpful to store values from the content of a page or a selected element.
For example if you use a selector to the given element, then the html content of this element will be stored. Furthermore there should be some possibility to also select attributes from the elements and their values.

**Comment by dimw** [comment]
Indeed, we have already discuss this topic with @build-failure. It would be suitable to have a `store` criterion on particular steps which stores the DOM element's metadata into an immutable variable, e.g.:

```
- ensure:
    selector: input[name=emailaddress]
    store: userEmailAddress
- enter:
    selector: input[id=emailAddressRepeat]
    input: '${userEmailAddress.val}'
```

Further, it could be reasonable to have some default jQuery-like namespacing for property access, which may look as following:
- `userEmailAddress.val` - is equivalent to `jQuery('...').val()`
- `userEmailAddress.html` - is equivalent to `jQuery('...').html()`
- `userEmailAddress.text` - is equivalent to `jQuery('...').text()`
- `userEmailAddress.attr.<attribute name>` - is equivalent to `jQuery('...').attr('<attribute name>')`
- (optional) `userEmailAddress.prop.<attribute name>` - is equivalent to `jQuery('...').prop('<attribute name>')`
