### ISSUE TITLE
Misunderstanding the 'store' step notation

### ISSUE THREAD

**Issue by sbathke** [automate-website/waml#13]
If I use the store step with only one value to store and also using a condition it would look like this for me:

```yaml
- store:
    variableName: 'blakeks'
    if: ${condition}
```

But this is a combination of the short notation for value within the 'store' step, which is not clear for the parser.
So I have to write:

```yaml
- store:
  value:
    variableName: 'blakes'
  if: ${condition}
```

Is there a way to make this more self-explaining to the reader? Or could you use probably a better warning instead of:

    Caused by: website.automate.waml.io.deserializer.UnknownCriterionException: Unknown criterion variableName for step store. Valid criteria are [value, unless, if, meta].
