### ISSUE TITLE
Add support for drag and drop

### ISSUE THREAD

**Issue by dimw** [automate-website/waml#15]
WAML needs an action to support drag and drop. This could look like:

```yaml
steps:
- dragAndDrop:
    source: "<css selector/element>"
    target: "<css selector/element>"
```

Alternatively, the existing `click` action could be used, but this could be less transparent, e.g.:

```yaml
steps:
- click:
    selector: "<css selector>"
    dropOn: "<css selector/element>"
```
