### ISSUE TITLE
Add support for alert/confirm/prompt handling

### ISSUE THREAD

**Issue by dimw** [automate-website/waml#16]
WAML should support alert/confirm/prompt methods.

I.e. the following notation could be used to accept alert (pressing OK button):
```yaml
- alert: 
    confirm: true   # true: pressing OK button; false: pressing cancel button
    input: '<some input>' # input for prompt
    text: '<text shown on the alert/confirm/prompt>' # text which appears on the alert
```
Whereby `accept` could be the default criteria for the shout notation:
```yaml
- alert: true
```

Alternatively, it could be consider to have one action for each alert type.
