### ISSUE TITLE
Add support for plain JavaScript injection and execution

### ISSUE THREAD

**Issue by dimw** [automate-website/waml#17]
As a developer
I want to have an `execute` action for WAML 
so that I can execute JavaScript in the context of the web page and thus perform complex manipulations on the test object.

E.g.:

```yaml
- execute: |
     document.body.style.backgroundColor = "red";
```

**Comment by dimw** [comment]
There should be different approaches how to define a evaluation step within WAML which consider:
- Synchronous calls
- Synchronous calls with context
- Asynchronous calls
- Asynchronous calls with context

**Further, it should be defined whether or how the returned object is considered.**

## Synchronous Calls
The following approach should be used for for simple synchronous calls:

> A variable in local storage should be modified.

```yaml
steps:
- execute: "localStorage.setItem('lastLoginDate', '2017-01-01');"
```

Or this when using multi-line notation:

> The appearance of the page should be modified.

```yaml
steps:
- execute:
    script: >
      var element = document.getElementById('loading-indicator');
      element.style.display = 'none';
```

## Synchronous Calls with Context
For more complex scenarios which require the current context, the following structure should be used.

> The document background color should be set to the value defined in the execution context.

```yaml
steps:
- execute:
    with_context: true # default value: false
    script: >
      function (context) {
        document.body.bgColor = context.backgroundColor;
      }
```

## Asynchronous Calls with Context
Async call for more complex use-cases.

> The user profile should be provided from the endpoint and stored to the context.

```yaml
steps:
- execute:
    with_context: true # default value: false
    async: true # default value: false
    script: >
      function (context, callback) {
          $.get( "/user/profile")
             .done(function (data) {
                 context.userProfile = data;
             })
             .always(function () {           
               callback();
             });
      }
```
