### ISSUE TITLE
Add helpful snippets [responsive viewports, etc].

### ISSUE THREAD

**Issue by mklemersson** [automate-website/waml#19]
The main goal here is to create some snippets in order to export/add some variables like a template.

E.G
```yaml
# _mobile.waml
- when: ${isPhone}
  define:
    display_resolution: '320x320' # we can check a better aspect ratio
    isDesktop: false
    maxWidth: 479
    minWidth: 320

# _tablet.waml
- when: ${isTablet}
  define:
    display_resolution: '768x350'
    isDesktop: false
    maxWidth: 991
    minWidth: 768
```

Or we can wrap everything like this above in one file called `_responsive.waml`
